services:
  pg:
    container_name: pg_db
    image: postgres
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cnfccnfc228
    ports:
      - "5438:5432"


  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"

  fastapi:
    build: .
    container_name: fastapi_app
    command: ["/app/app.sh"]
    ports:
      - "8008:8008"
    depends_on:
      - pg
      - pgadmin